# Generated by Django 4.1.4 on 2022-12-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('select_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetypes')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
