# Generated by Django 4.1.4 on 2022-12-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_enquiry_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='pending',
            new_name='service_status',
        ),
    ]
