# Generated by Django 4.1.4 on 2022-12-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_pending_enquiry_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
