# Generated by Django 4.1.4 on 2022-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_newsletter_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypes',
            name='quote',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer gravida mauris non mi gravida, at sollicitudin.'),
        ),
    ]
