# Generated by Django 4.1.4 on 2022-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicetypes_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypes',
            name='service_image',
            field=models.ImageField(default='path/to/static/images/g1', upload_to='service_images'),
        ),
    ]
