# Generated by Django 4.1.4 on 2022-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicetypes_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypes',
            name='service_image',
            field=models.ImageField(default='service_images/default.jpg', upload_to='service_images/'),
        ),
    ]
