# Generated by Django 4.1.4 on 2022-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicetypes_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_images')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
