# Generated by Django 4.1.4 on 2022-12-12 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
