# Generated by Django 4.1.4 on 2022-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_images')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
