# Generated by Django 4.1.4 on 2022-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientquotes',
            options={'verbose_name_plural': 'Client Quotes'},
        ),
        migrations.AddField(
            model_name='message',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
